image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install && yarn run build
    command: yarn serve

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - octref.vetur@0.24.0:FtNScOJHzSTxcNY6NB60Cg==